table dim_brand
	lineageTag: e3daa9ed-321f-480b-ba6c-b48c6d90ab87

	column brand_id
		dataType: int64
		formatString: 0
		lineageTag: e69fd57c-1b59-465c-a0e2-c0b05561acd9
		summarizeBy: sum
		sourceColumn: brand_id

		annotation SummarizationSetBy = Automatic

	column brand_name
		dataType: string
		lineageTag: f6a998a7-b582-4172-a47d-7cd976fedfa1
		summarizeBy: none
		sourceColumn: brand_name

		annotation SummarizationSetBy = Automatic

	partition dim_brand = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("E:\Final_project\Customer Reviews Sentiment\Customer Reviews Sentiment\outputs\bi_export\dim_brand.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"brand_id", Int64.Type}, {"brand_name", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

